//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Malaria_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FAQ
    {
        public int FAQ_ID { get; set; }
        public Nullable<int> About_Malaria_ID { get; set; }
        public string FAQ_Question { get; set; }
        public string FAQ_Answer { get; set; }
    
        public virtual About_Malaria About_Malaria { get; set; }
    }
}
